name: Build and Test

on:
    push:
        branches:
          - "main"
    workflow_dispatch:

env:
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
  SOLUTION_PATH: ./src/NetExt.sln
  TESTS_PROJ_PATH: ./tests/NextExt.UnitTests/NextExt.UnitTests.csproj

permissions:
  contents: write

jobs:
  job-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository Owner
        run: |
          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
            echo "Unauthorized: Only the repository owner (${ github.repository_owner }) can trigger this workflow."
            exit 1
          fi
  run-tests:
    needs: job-verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x

      - name: Build
        run: dotnet build $SOLUTION_PATH -c Release

      - name: Run Tests
        run: dotnet test $TESTS_PROJ_PATH -c Release