name: Deploy package to nuget

on:
  push:
    branches:
      - "feature/init"
      - "main"
  workflow_dispatch:

env:
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
  PROJ_PATH: ./src/NetExt.Core/NetExt.Core.csproj
  TESTS_PROJ_PATH: ./tests/NextExt.Core.UnitTests/NextExt.Core.UnitTests.csproj

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x

      - name: Build Api
        run: dotnet build $PROJ_PATH -c Release

      - name: Run Tests
        run: dotnet test $TESTS_PROJ_PATH -c Release
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x

      - name: Pack NuGet package
        run: dotnet pack $PROJ_PATH -c Release --output ${{ github.workspace }}/nupkg

      - name: Push NuGet package
        run: |
          dotnet nuget push ${{ github.workspace }}/nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source $NUGET_SOURCE
