name: Deploy package to nuget

on:
  push:
    branches:
      - "feature/init"
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Api
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x
      - run: dotnet build ./src/NetExt.Core/NetExt.Core/NetExt.Core.csproj -c Release
        
