name: Deploy package to nuget server

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Choose the package"
        required: true
        type: choice
        options:
          - 'NextExt.Core'
          - 'NetExt.Models'

env:
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
  TESTS_PROJ_PATH: ./tests/NextExt.Core.UnitTests/NextExt.Core.UnitTests.csproj

permissions:
  contents: write

jobs:
  job-verification:
    runs-on: ubuntu-latest
    steps:
      # TODO: uncomment in main
      # - name: Check Main Branch
      #   run: |
      #     if [[ "${{ github.ref_name }}" != "main" ]]; then
      #       echo "This workflow can only be triggered on the 'main' branch."
      #       exit 1
      #     fi
      - name: Check Repository Owner
        run: |
          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
            echo "Unauthorized: Only the repository owner (${ github.repository_owner }) can trigger this workflow."
            exit 1
          fi

  job-tests:
    needs: job-verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x
      - name: Run Tests
        run: dotnet test $TESTS_PROJ_PATH -c Release

  job-NetExt_Core:
    needs: job-tests
    uses: ./.github/workflows/deploy-package-flow.yml
    if: ${{ inputs.package_name == 'NextExt.Core' }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    with:
      project_path: './src/NetExt.Core/NetExt.Core.csproj'
  
  job-NetExt_Models:
    needs: job-tests
    uses: ./.github/workflows/deploy-package-flow.yml
    if: ${{ inputs.package_name == 'NetExt.Models' }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    with:
      project_path: './src/NetExt.Models/NetExt.Models.csproj'
