name: Deploy package to nuget

on:
  push:
    branches:
      - "feature/init"
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x

      - name: Build Api
        run: dotnet build ./src/NetExt.Core/NetExt.Core/NetExt.Core.csproj -c Release

      - name: Run Tests
        run: dotnet test ./tests/NextExt.Core.UnitTests/NextExt.Core.UnitTests.csproj -c Release
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
            8.x.x
            7.x.x
            6.x.x

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Push NuGet package
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
